/**
 * Curated list of character style names for portrait generation.
 * The selected style replaces "tactical gear" in the image generation prompt.
 */
export const CHARACTER_STYLES: string[] = [
  '0core',
  'Acid panda',
  'Beastie',
  'Bitcrusher',
  'Bloodsport',
  'Cadavercore',
  'Codefolk',
  'Converter',
  'Corpodrone',
  'Cosmopunk',
  'Cvlt',
  'Cybercrust',
  'CyPop',
  'Daemonista',
  'Deathbloc',
  'Doomtroop',
  'Ghoul',
  'Glitchmode',
  'Goregrinder',
  'Gutterscum',
  'Hexcore',
  'Hype street',
  'Kill mode',
  'Meta',
  'Mimic',
  'Minimal',
  'Minotaur',
  'Mobwave',
  'Monsterwave',
  'Murdercore',
  'Necropop',
  'Neurotripper',
  'NuFlesh',
  'NuGoth',
  'NuPrep',
  'Oceanwave',
  'OG',
  'Old-school cyberpunk',
  'Orbital',
  'Postlife',
  'Pyrocore',
  'Razormouth',
  'Retro metal',
  'Riot kid',
  'Robomode',
  'Roller bruiser',
  'Technoir',
  'Trad punk',
  'Wallgoth',
  'Waster',
];
