/**
 * Character name table for 28 Psalms ruleset
 * Used for random character name generation
 */

export const characterNames28Psalms: string[] = [
  'Gridotus',
  'Mister Quimper',
  'Inquisitor Lucius',
  'David C. Moore',
  'Zachary Knippel',
  'Capitald',
  'Matthias Mencel',
  'William B',
  'Zac Mazey',
  'The Dour Kin',
  'Gabe Benavides',
  'Robert Lee',
  'Paul Wilson',
  'Abby',
  'Cecil',
  'George Kaldis',
  'Shawn Turpin',
  'Kiral',
  'Charles Chapman',
  'Dennis McGeen',
  'ElDavePhoto',
  'Fenrikson',
  'Nick',
  'shawn hakl',
  'Alexander',
  '(_><)',
  'DerOlfork',
  'Devon Tackett',
  'Christopher Moses',
  'CHBRey',
  'Marco "Sagojo" Tripepi',
  'F. Oiche',
  'Roger J Porter',
  'Koji Chihuahua',
  'Pierre le Griffon',
  'Benny Harvey',
  'Auston J Butler',
  'Timothy Morrison',
  'Eric Jackson',
  'Paul Lukianchuk',
  '12ozmousse',
  'Richard Smeeton',
  'Benjamin K. Arvel',
  'Roger pagate algo',
  'David Bagdan',
  'Honda Ramone',
  'Stelios',
  'J T',
  'Ryan',
  'Grunt Chutney',
  'Zak Knippel',
  'Rex',
  'Mister Quimper',
  'Ymön',
  'Brett',
  'Christian Taylor',
  'Grimbleshank Brumblekramps',
  'Elijah',
  'Matthew',
  'Bakch',
  'Paul Gothard',
  'Bolty McBoltface',
  'Tim "Trench" Young',
  'Flynn Somnderian',
  'Tannhausyr',
  'Dominic Godber',
  "Rad 'killabuser' Betayeb",
  'The Whumpus',
  'Leilum',
  'Pä the Annihilator',
  "Nay'ten",
  'Justizius',
  'Marty',
  'Felix',
  'Cunabula',
  '[NAME.LEFT.BLANK]',
  'LUURANKO',
  'Keihin',
  'Cheesy Charlie',
  'Jason',
  'Ophelia',
  'Alex Goode',
  'John R. Young',
  'Merlin',
  'Brezhnev Casazza',
  'jet0ne',
  'Toll Odr',
  'P C Hogan',
  'Boychuk',
  'KA1Z3R',
  'Ser Alexander of House Ourique',
  'Forgot to check email',
  'Did not read the Terms and Conditions',
  'Missing in Action',
  'Sleeping',
  'Failed to follow orders',
  'N/A',
  'Michale clark',
  'Craig',
  'Filthor',
];
