/**
 * Curated list of character feature descriptors for portrait generation.
 * The selected feature is included in the image generation prompt to
 * add a distinctive visual characteristic to the character portrait.
 */
export const CHARACTER_FEATURES: string[] = [
  'Abundance of rings',
  'All monochrome',
  'Artificial skin',
  'Beastlike',
  'Broken nose',
  'Burn scars',
  'Completely hairless',
  'Cosmetic gills',
  'Covered in tattoos',
  'Customized voicebox',
  'Disheveled look',
  'Dollfaced',
  'Dueling scars',
  'Elaborate hairstyle',
  'Enhanced cheekbones',
  'Fluorescent veins',
  'Forehead display',
  'Giant RCD helmet rig',
  'Glitterskin',
  'Glowing respirator',
  'Golden grillz',
  'Headband',
  'Heavy on the makeup',
  'Holomorphed face',
  'Interesting perfume',
  'Lace trimmings',
  'Laser branded',
  'Lipless—just teeth',
  'Mirror eyes',
  'More plastic than skin',
  'Necrotic face',
  'Nonhuman ears',
  'Palms covered in notes',
  'Pattern overdose',
  'Plenty of piercings',
  'Radiant eyebrows',
  'Rainbow haircut',
  'Ritual scarifications',
  'Robotlike',
  'Shoulder pads',
  'Subdermal implants',
  'Tons of jewelry',
  'Traditional amulets',
  'Translucent skin',
  'Transparent wear',
  'Unkempt hair',
  'Unnatural eyes',
  'UV-inked face',
  'VIP lookalike',
  'War paints',
];
