/**
 * KSP Equipment Data
 */

import { Weapon, Armor, Item, Ammo, Consumable, Drone } from './index';

// ============================================================================
// WEAPONS
// ============================================================================

export const weaponsKSP: Weapon[] = [
  // ============ ONE-HANDED RANGED ============
  {
    id: 'revolver',
    name: 'Revolver',
    damage: 'D6',
    modifier: 'presence',
    cost: 100,
    slots: 1,
    isTwoHanded: false,
    category: 'weapon',
    specialRules: ['Ranged', 'Reload 5'],
    isRanged: true,
  },
  {
    id: 'smart-pistol',
    name: 'Smart Pistol',
    damage: 'D6',
    modifier: 'presence',
    cost: 110,
    slots: 1,
    isTwoHanded: false,
    category: 'weapon',
    specialRules: ['Ranged', 'Cyber', 'Reload 6'],
    isRanged: true,
  },
  {
    id: 'heavy-pistol',
    name: 'Heavy Pistol',
    damage: 'D8',
    modifier: 'strength',
    cost: 120,
    slots: 1,
    isTwoHanded: false,
    category: 'weapon',
    specialRules: ['Ranged', 'Cyber', 'Reload 4'],
    isRanged: true,
  },
  {
    id: 'tazer',
    name: 'Tazer',
    damage: '-',
    modifier: 'agility',
    cost: 100,
    slots: 1,
    isTwoHanded: false,
    category: 'weapon',
    specialRules: ['Non-lethal', 'Ranged 6', 'Reload'],
    isRanged: true,
  },

  // ============ TWO-HANDED RANGED ============
  {
    id: 'ancient-rifle',
    name: 'Ancient Rifle',
    damage: 'D8',
    modifier: 'presence',
    cost: 200,
    slots: 2,
    isTwoHanded: true,
    category: 'weapon',
    specialRules: ['AF2', 'Ranged', 'Jam', 'Reload 5'],
    isRanged: true,
  },
  {
    id: 'sawed-off',
    name: 'Sawed-off',
    damage: 'D8',
    modifier: 'presence',
    cost: 150,
    slots: 2,
    isTwoHanded: true,
    category: 'weapon',
    specialRules: ['Explode', 'Ranged 6', 'Reload 2'],
    isRanged: true,
  },
  {
    id: 'smart-rifle',
    name: 'Smart Rifle',
    damage: 'D8',
    modifier: 'presence',
    cost: 250,
    slots: 2,
    isTwoHanded: true,
    category: 'weapon',
    specialRules: ['AF2', 'Ranged 15', 'Cyber', 'Reload 4'],
    isRanged: true,
  },
  {
    id: 'smart-smg',
    name: 'Smart SMG',
    damage: 'D6',
    modifier: 'presence',
    cost: 225,
    slots: 2,
    isTwoHanded: true,
    category: 'weapon',
    specialRules: ['AF2', 'Ranged', 'Cyber', 'Reload 4'],
    isRanged: true,
  },
  {
    id: 'pulse-rifle',
    name: 'Pulse Rifle',
    damage: 'D10',
    modifier: 'presence',
    cost: 300,
    slots: 2,
    isTwoHanded: true,
    category: 'weapon',
    specialRules: ['AF3', 'Ranged 15', 'Cyber', 'Reload 5', 'Can be loaded with a Consumable in addition to ammo which can be fired up to 12 inches'],
    isRanged: true,
  },
  {
    id: 'arc-gun',
    name: 'Arc Gun',
    damage: '2D10',
    modifier: 'strength',
    cost: 500,
    slots: 2,
    isTwoHanded: true,
    category: 'weapon',
    specialRules: ['Bulky', 'Ranged', 'Cyber', 'Reload', 'Explode', 'AP'],
    isRanged: true,
  },
  {
    id: 'guided-rifle',
    name: 'Guided Rifle',
    damage: '2D10',
    modifier: 'presence',
    cost: 600,
    slots: 2,
    isTwoHanded: true,
    category: 'weapon',
    specialRules: ['Jam', 'Ranged 24', 'Cyber', 'Reload', 'When used with a Smart link or Augmented Helmet does not need line of sight to target.'],
    isRanged: true,
  },
  {
    id: 'cyber-crossbow',
    name: 'Cyber Crossbow',
    damage: '1D10',
    modifier: 'presence',
    cost: 250,
    slots: 2,
    isTwoHanded: true,
    category: 'weapon',
    specialRules: ['Ranged', 'Cyber', 'Reload'],
    isRanged: true,
  },

  // ============ ONE-HANDED MELEE ============
  {
    id: 'knife',
    name: 'Knife',
    damage: 'D4',
    modifier: 'agility',
    cost: 50,
    slots: 1,
    isTwoHanded: false,
    category: 'weapon',
    specialRules: ['Thrown'],
    isRanged: false,
  },
  {
    id: 'baton',
    name: 'Baton',
    damage: 'D4',
    modifier: 'strength',
    cost: 50,
    slots: 1,
    isTwoHanded: false,
    category: 'weapon',
    specialRules: ['Critical Causes Dazed'],
    isRanged: false,
  },
  {
    id: 'steel-pipe',
    name: 'Steel Pipe',
    damage: 'D4',
    modifier: 'strength',
    cost: 0,
    slots: 1,
    isTwoHanded: false,
    category: 'weapon',
    specialRules: ['Counts as Makeshift Weapon'],
    isRanged: false,
  },
  {
    id: 'mono-sword',
    name: 'MonoSword',
    damage: 'D8',
    modifier: 'agility',
    cost: 200,
    slots: 1,
    isTwoHanded: false,
    category: 'weapon',
    specialRules: ['AP'],
    isRanged: false,
  },
  {
    id: 'broken-bottle',
    name: 'Broken Bottle',
    damage: 'D4',
    modifier: 'agility',
    cost: 0,
    slots: 1,
    isTwoHanded: false,
    category: 'weapon',
    specialRules: ['Criticals cause bleeding. Fumbling with this weapon hurts the model using it.'],
    isRanged: false,
  },
  {
    id: 'power-tool',
    name: 'Power Tool',
    damage: 'D6',
    modifier: 'strength',
    cost: 150,
    slots: 1,
    isTwoHanded: false,
    category: 'weapon',
    specialRules: ['Bulky', 'Cyber'],
    isRanged: false,
  },
  {
    id: 'stun-baton',
    name: 'Stun Baton',
    damage: '-',
    modifier: 'strength',
    cost: 100,
    slots: 1,
    isTwoHanded: false,
    category: 'weapon',
    specialRules: ['Non-lethal'],
    isRanged: false,
  },
];

export const armorKSP: Armor[] = [
  {
    id: 'home-made',
    name: 'Home Made',
    av: 1,
    cost: 0,
    slots: 1,
    category: 'armor',
    specialRules: 'User suffers -1 Agility.',
    statModifiers: { agility: -1 },
  },
  {
    id: 'corp-sec',
    name: 'Corp-Sec',
    av: 1,
    cost: 200,
    slots: 1,
    category: 'armor',
    specialRules: 'Standard issue private military grade.',
  },
  {
    id: 'bike-helmet',
    name: 'Bike Helmet',
    av: 0,
    cost: 50,
    slots: 1,
    category: 'armor',
    specialRules: 'Wearer is immune to Dazed.',
  },
  {
    id: 'grounded',
    name: 'Grounded',
    av: 2,
    cost: 300,
    slots: 1,
    category: 'armor',
    specialRules: 'Wearer is immune to stun effect.',
  },
  {
    id: 'soft-plates',
    name: 'Soft Plates',
    av: 1,
    cost: 300,
    slots: 1,
    category: 'armor',
    specialRules: 'Will stop a knife but not a bullet. AV 1 vs ranged, 3 vs melee.',
  },
  {
    id: 'plate-carrier',
    name: 'Plate Carrier',
    av: 3,
    cost: 500,
    slots: 1,
    category: 'armor',
    specialRules: 'User suffers -3 to all Agility tests but movement remains the same.',
    statModifiers: {
      agility: -3,
      movement: 3,
    },
  },
  {
    id: 'exo-skeleton',
    name: 'Exo Skeleton',
    av: 2,
    cost: 1500,
    slots: 1,
    category: 'armor',
    specialRules: '[Cyber] Strength stat +3.',
    statModifiers: { strength: 3 },
  },
  {
    id: 'augmented-helmet',
    name: 'Augmented Helmet',
    av: 1,
    cost: 200,
    slots: 1,
    category: 'armor',
    specialRules: '[Cyber] Wearer is immune to Dazed. Also provides a heads up display granting +1 to shoot with weapons with Cyber keyword.',
  },
  {
    id: 'reactive',
    name: 'Reactive',
    av: 1,
    cost: 300,
    slots: 1,
    category: 'armor',
    specialRules: '[Cyber] Wearer ignores Critical hits.',
  },
  {
    id: 'vengeance',
    name: 'Vengeance',
    av: 2,
    cost: 500,
    slots: 1,
    category: 'armor',
    specialRules: '[Cyber] When hit with a melee weapon, attacker takes 1D4 damage.',
  },
];

export const itemsKSP: Item[] = [];
export const ammoKSP: Ammo[] = [];
export const consumablesKSP: Consumable[] = [
  {
    id: 'molotov',
    name: 'Molotov',
    damage: 'D6',
    modifier: 'agility',
    cost: 50,
    slots: 1,
    category: 'consumable',
    specialRules: ['Burn', 'Explode', 'Thrown'],
  },
  {
    id: 'smoke-grenade',
    name: 'Smoke Grenade',
    damage: '-',
    modifier: 'agility',
    cost: 50,
    slots: 1,
    category: 'consumable',
    specialRules: ['Smoke', 'Template', 'Thrown'],
  },
  {
    id: 'tear-gas-grenade',
    name: 'TearGas Grenade',
    damage: '-',
    modifier: 'agility',
    cost: 60,
    slots: 1,
    category: 'consumable',
    specialRules: ['Gas', 'Template', 'Thrown'],
  },
  {
    id: 'homemade-bomb',
    name: 'Homemade bomb',
    damage: 'D6',
    modifier: 'strength',
    cost: 20,
    slots: 1,
    category: 'consumable',
    specialRules: ['Explode', 'Thrown'],
  },
  {
    id: 'grenade',
    name: 'Grenade',
    damage: 'D8',
    modifier: 'agility',
    cost: 50,
    slots: 1,
    category: 'consumable',
    specialRules: ['Explode', 'Called Shot', 'Thrown'],
  },
  {
    id: 'stun-grenade',
    name: 'Stun Grenade',
    damage: '-',
    modifier: 'agility',
    cost: 50,
    slots: 1,
    category: 'consumable',
    specialRules: ['Non-lethal', 'Thrown'],
  },
  {
    id: 'c9',
    name: 'C9',
    damage: '1D10',
    modifier: 'presence',
    cost: 90,
    slots: 1,
    category: 'consumable',
    specialRules: ['Explode', 'Thrown', 'As an action can be placed on a piece of terrain smaller than 6x6 to remove it from play.'],
  },
  {
    id: 'omega-bomb',
    name: 'ΑΩ Bomb',
    damage: '∞',
    modifier: 'knowledge',
    cost: 99000,
    slots: 1,
    category: 'consumable',
    specialRules: ['Destroys the whole world, kills everyone'],
  },
];

export const dronesKSP: Drone[] = [
  {
    id: 'proxy-robot',
    name: 'Proxy Robot',
    cost: 500,
    slots: 0,
    category: 'drone',
    hp: null,
    av: null,
    specialRules: 'Replaces a crewmember in a Scenario. Immune to Disease, Gas and Poison. [Cyber]',
    statModifiers: {
      agility: -1,
      knowledge: -1,
      presence: -1,
      strength: 3,
      toughness: 2,
    },
    allowAI: false,
    isAI: false,
  },
  {
    id: 'military-drone',
    name: 'Military Drone',
    cost: 400,
    slots: 1,
    category: 'drone',
    hp: 6,
    av: 2,
    specialRules: 'Can have any weapon from page 27 attached. Carries 1 mag of Ammo for the attached gun. Can only be reloaded between Scenarios. Can make a single ranged attack per round.',
    allowAI: true,
    isAI: false,
  },
  {
    id: 'medic-drone',
    name: 'Medic Drone',
    cost: 200,
    slots: 1,
    category: 'drone',
    hp: 5,
    av: 1,
    specialRules: 'Can heal a model within 1 inch for 1D6 HP.',
    allowAI: true,
    isAI: false,
  },
  {
    id: 'recon-drone',
    name: 'Recon Drone',
    cost: 100,
    slots: 1,
    category: 'drone',
    hp: 3,
    av: 1,
    specialRules: 'Can interact with items and Scenario objectives, including picking up 1 item and looting.',
    allowAI: true,
    isAI: false,
  },
];
