/**
 * Equipment data for 28 Psalms ruleset
 * Organized by category and tech level
 */

import { Item, Ammo, Armor, Weapon, Consumable } from './index';

// ============================================================================
// TECH-AGNOSTIC EQUIPMENT
// ============================================================================

export const items28Psalms: Item[] = [
  {
    id: 'cheese',
    name: 'Cheese',
    ability: 'Can be eaten as an action to heal 1 HP',
    cost: 3,
    slots: 1,
    category: 'item',
    techLevel: null,
  },
  {
    id: 'tincture',
    name: 'Tincture',
    ability: 'Can be taken to remove Poison and Disease',
    cost: 7,
    slots: 1,
    category: 'item',
    techLevel: null,
  },
  {
    id: 'bandage',
    name: 'Bandage',
    ability: 'Cures Bleeding',
    cost: 1,
    slots: 1,
    category: 'item',
    techLevel: null,
  },
  {
    id: 'potion-stimpack',
    name: 'Potion/Stimpack',
    ability: 'Heals 1D6 HP',
    cost: 6,
    slots: 1,
    category: 'item',
    techLevel: null,
  },
  {
    id: 'hacking-deck',
    name: 'Hacking Deck',
    ability: 'Allows hacking',
    cost: 20,
    slots: 1,
    category: 'item',
    techLevel: 'future-tech',
  },
];

export const ammo28Psalms: Ammo[] = [
  {
    id: 'bow-ammo',
    name: 'Bow',
    shots: 5,
    cost: 1,
    slots: 1,
    category: 'ammo',
    techLevel: null,
    compatibleWeapons: ['bow', 'crossbow'],
  },
  {
    id: 'revolver-ammo',
    name: 'Revolver',
    shots: 5,
    cost: 3,
    slots: 1,
    category: 'ammo',
    techLevel: 'past-tech',
    compatibleWeapons: ['revolver', 'molten-slug-gun'],
  },
  {
    id: 'pistol-ammo',
    name: 'Pistol',
    shots: 6,
    cost: 4,
    slots: 1,
    category: 'ammo',
    techLevel: 'past-tech',
    compatibleWeapons: ['pistol'],
  },
  {
    id: 'space-rifle-ammo',
    name: 'Space Rifle',
    shots: 4,
    cost: 5,
    slots: 1,
    category: 'ammo',
    techLevel: 'future-tech',
    compatibleWeapons: ['space-rifle'],
  },
  {
    id: 'pulse-rifle-ammo',
    name: 'Pulse Rifle',
    shots: 5,
    cost: 4,
    slots: 1,
    category: 'ammo',
    techLevel: 'future-tech',
    compatibleWeapons: ['pulse-rifle'],
  },
  {
    id: 'plasma-cell-ammo',
    name: 'Plasma Cell',
    shots: 2,
    cost: 10,
    slots: 1,
    category: 'ammo',
    techLevel: 'future-tech',
    compatibleWeapons: ['plasma-rifle'],
  },
  {
    id: 'flame-ammo',
    name: 'Flame',
    shots: 1,
    cost: 5,
    slots: 1,
    category: 'ammo',
    techLevel: 'past-tech',
    compatibleWeapons: ['flamethrower'],
  },
  {
    id: 'laser-ammo',
    name: 'Laser',
    shots: 12,
    cost: 12,
    slots: 1,
    category: 'ammo',
    techLevel: 'future-tech',
    compatibleWeapons: ['laser-rifle'],
  },
];

export const armor28Psalms: Armor[] = [
  {
    id: 'light-armor',
    name: 'Light',
    av: 1,
    cost: 2,
    slots: 1,
    category: 'armor',
    specialRules: '',
    techLevel: null,
  },
  {
    id: 'medium-armor',
    name: 'Medium',
    av: 2,
    cost: 10,
    slots: 1,
    category: 'armor',
    specialRules: '',
    techLevel: null,
  },
  {
    id: 'heavy-armor',
    name: 'Heavy',
    av: 3,
    cost: 20,
    slots: 1,
    category: 'armor',
    specialRules: '',
    techLevel: null,
  },
  {
    id: 'power-plate-armor',
    name: 'Power/Plate',
    av: 4,
    cost: 50,
    slots: 1,
    category: 'armor',
    specialRules: 'Must have 2+ Strength to use',
    requiredStrength: 2,
    techLevel: null,
  },
  {
    id: 'homemade-armor',
    name: 'Homemade',
    av: 1,
    cost: 0,
    slots: 1,
    category: 'armor',
    specialRules: '-1 movement',
    movementModifier: -1,
    techLevel: null,
  },
];

// ============================================================================
// PAST TECH WEAPONS
// ============================================================================

export const pastTechWeapons28Psalms: Weapon[] = [
  // One-handed Melee Weapons
  {
    id: 'dagger',
    name: 'Dagger',
    damage: 'D4',
    modifier: 'agility',
    specialRules: ['Thrown'],
    cost: 1,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'sword',
    name: 'Sword',
    damage: 'D6',
    modifier: 'strength',
    specialRules: [],
    cost: 3,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'axe',
    name: 'Axe',
    damage: 'D6',
    modifier: 'strength',
    specialRules: ['Thrown'],
    cost: 3,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'flail',
    name: 'Flail',
    damage: 'D8',
    modifier: 'strength',
    specialRules: ['Critical cause Bleeding'],
    cost: 5,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'makeshift-1h',
    name: 'Makeshift (1-hand)',
    damage: 'D4',
    modifier: 'strength',
    specialRules: [],
    cost: 0,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'torch',
    name: 'Torch',
    damage: 'D4',
    modifier: 'strength',
    specialRules: ['Burn'],
    cost: 1,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'past-tech',
  },

  // Two-handed Melee Weapons
  {
    id: 'great-axe',
    name: 'Great Axe',
    damage: 'D10',
    modifier: 'strength',
    specialRules: ['Criticals break enemy weapons'],
    cost: 10,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'bastard-sword',
    name: 'Bastard Sword',
    damage: 'D10',
    modifier: 'strength',
    specialRules: ['Criticals break enemy weapons'],
    cost: 10,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'spear',
    name: 'Spear',
    damage: 'D6',
    modifier: 'agility',
    specialRules: ['Reach', 'Thrown'],
    cost: 8,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'makeshift-2h',
    name: 'Makeshift (2-hand)',
    damage: 'D6',
    modifier: 'strength',
    specialRules: [],
    cost: 0,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: false,
    techLevel: 'past-tech',
  },

  // Bows (Ranged, 2 slots, includes free am*
