/**
 * Equipment data for 28 Psalms ruleset
 * Organized by category and tech level
 */

import { Item, Ammo, Armor, Weapon } from './index';

// ============================================================================
// TECH-AGNOSTIC EQUIPMENT
// ============================================================================

export const items28Psalms: Item[] = [
  {
    id: 'cheese',
    name: 'Cheese',
    ability: 'Can be eaten as an action to heal 1 HP',
    cost: 3,
    slots: 1,
    category: 'item',
    techLevel: undefined,
  },
  {
    id: 'tincture',
    name: 'Tincture',
    ability: 'Can be taken to remove Poison and Disease',
    cost: 7,
    slots: 1,
    category: 'item',
    techLevel: undefined,
  },
  {
    id: 'bandage',
    name: 'Bandage',
    ability: 'Cures Bleeding',
    cost: 1,
    slots: 1,
    category: 'item',
    techLevel: undefined,
  },
  {
    id: 'potion-stimpack',
    name: 'Potion/Stimpack',
    ability: 'Heals 1D6 HP',
    cost: 6,
    slots: 1,
    category: 'item',
    techLevel: undefined,
  },
  {
    id: 'hacking-deck',
    name: 'Hacking Deck',
    ability: 'Allows hacking',
    cost: 20,
    slots: 1,
    category: 'item',
    techLevel: 'future-tech',
  },
];

export const ammo28Psalms: Ammo[] = [
  {
    id: 'bow-ammo',
    name: 'Bow',
    shots: 5,
    cost: 1,
    slots: 1,
    category: 'ammo',
    techLevel: undefined,
    compatibleWeapons: ['bow', 'crossbow'],
  },
  {
    id: 'revolver-ammo',
    name: 'Revolver',
    shots: 5,
    cost: 3,
    slots: 1,
    category: 'ammo',
    techLevel: 'past-tech',
    compatibleWeapons: ['revolver', 'molten-slug-gun'],
  },
  {
    id: 'pistol-ammo',
    name: 'Pistol',
    shots: 6,
    cost: 4,
    slots: 1,
    category: 'ammo',
    techLevel: 'past-tech',
    compatibleWeapons: ['pistol'],
  },
  {
    id: 'space-rifle-ammo',
    name: 'Space Rifle',
    shots: 4,
    cost: 5,
    slots: 1,
    category: 'ammo',
    techLevel: 'future-tech',
    compatibleWeapons: ['rifle'],
  },
  {
    id: 'pulse-rifle-ammo',
    name: 'Pulse Rifle',
    shots: 5,
    cost: 4,
    slots: 1,
    category: 'ammo',
    techLevel: 'future-tech',
    compatibleWeapons: ['pulse-rifle'],
  },
  {
    id: 'plasma-cell-ammo',
    name: 'Plasma Cell',
    shots: 2,
    cost: 10,
    slots: 1,
    category: 'ammo',
    techLevel: 'future-tech',
    compatibleWeapons: ['plas-mar'],
  },
  {
    id: 'flame-ammo',
    name: 'Flame',
    shots: 1,
    cost: 5,
    slots: 1,
    category: 'ammo',
    techLevel: 'past-tech',
    compatibleWeapons: ['flamethrower'],
  },
  {
    id: 'laser-ammo',
    name: 'Laser',
    shots: 12,
    cost: 12,
    slots: 1,
    category: 'ammo',
    techLevel: 'future-tech',
    compatibleWeapons: ['laser'],
  },
  {
    id: 'shotgun-ammo',
    name: 'Shotgun',
    shots: 8,
    cost: 5,
    slots: 1,
    category: 'ammo',
    techLevel: 'future-tech',
    compatibleWeapons: ['shotgun'],
  },
];

export const armor28Psalms: Armor[] = [
  {
    id: 'light-armor',
    name: 'Light',
    av: 1,
    cost: 2,
    slots: 1,
    category: 'armor',
    specialRules: '',
    techLevel: undefined,
  },
  {
    id: 'medium-armor',
    name: 'Medium',
    av: 2,
    cost: 10,
    slots: 1,
    category: 'armor',
    specialRules: '',
    techLevel: undefined,
  },
  {
    id: 'heavy-armor',
    name: 'Heavy',
    av: 3,
    cost: 20,
    slots: 1,
    category: 'armor',
    specialRules: '',
    techLevel: undefined,
  },
  {
    id: 'power-plate-armor',
    name: 'Power/Plate',
    av: 4,
    cost: 50,
    slots: 1,
    category: 'armor',
    specialRules: 'Must have 2+ Strength to use',
    requiredStrength: 2,
    techLevel: undefined,
  },
  {
    id: 'homemade-armor',
    name: 'Homemade',
    av: 1,
    cost: 0,
    slots: 1,
    category: 'armor',
    specialRules: '-1 movement',
    movementModifier: -1,
    techLevel: undefined,
  },
];

// ============================================================================
// PAST TECH WEAPONS
// ============================================================================

export const pastTechWeapons28Psalms: Weapon[] = [
  // One-handed Melee Weapons
  {
    id: 'dagger',
    name: 'Dagger',
    damage: 'D4',
    modifier: 'agility',
    specialRules: ['Thrown'],
    cost: 1,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'sword',
    name: 'Sword',
    damage: 'D6',
    modifier: 'strength',
    specialRules: [],
    cost: 3,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'axe',
    name: 'Axe',
    damage: 'D6',
    modifier: 'strength',
    specialRules: ['Thrown'],
    cost: 3,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'flail',
    name: 'Flail',
    damage: 'D8',
    modifier: 'strength',
    specialRules: ['Critical cause Bleeding'],
    cost: 5,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'makeshift-1h',
    name: 'Makeshift (1-hand)',
    damage: 'D4',
    modifier: 'strength',
    specialRules: [],
    cost: 0,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'torch',
    name: 'Torch',
    damage: 'D4',
    modifier: 'strength',
    specialRules: ['Burn'],
    cost: 1,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'skull',
    name: 'Skull',
    damage: 'D4',
    modifier: 'strength',
    specialRules: ['Only for characters with the "skull" feat'],
    cost: 0,
    slots: 0,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'past-tech',
  },

  // Two-handed Melee Weapons
  {
    id: 'great-axe',
    name: 'Great Axe',
    damage: 'D10',
    modifier: 'strength',
    specialRules: ['Criticals break enemy weapons'],
    cost: 10,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'bastard-sword',
    name: 'Bastard Sword',
    damage: 'D10',
    modifier: 'strength',
    specialRules: ['Criticals break enemy weapons'],
    cost: 10,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'spear',
    name: 'Spear',
    damage: 'D6',
    modifier: 'agility',
    specialRules: ['Reach', 'Thrown'],
    cost: 8,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'makeshift-2h',
    name: 'Makeshift (2-hand)',
    damage: 'D6',
    modifier: 'strength',
    specialRules: [],
    cost: 0,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: false,
    techLevel: 'past-tech',
  },

  // Bows (Ranged, 2 slots, includes free ammo)
  {
    id: 'bow',
    name: 'Bow',
    damage: 'D6',
    modifier: 'presence',
    specialRules: ['Reload', 'Ranged'],
    cost: 5,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: true,
    ammoTypeId: 'bow-ammo',
    includesAmmoId: 'bow-ammo',
    techLevel: 'past-tech',
  },
  {
    id: 'crossbow',
    name: 'Crossbow',
    damage: 'D6',
    modifier: 'presence',
    specialRules: ['Reload', 'Ranged', 'Cruel'],
    cost: 8,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: true,
    ammoTypeId: 'bow-ammo',
    includesAmmoId: 'bow-ammo',
    techLevel: 'past-tech',
  },

  // Consumables (treated as weapons in squad builder)
  {
    id: 'molotov',
    name: 'Molotov',
    damage: 'D6',
    modifier: 'agility',
    specialRules: ['Burn', 'Explode', 'Thrown'],
    cost: 3,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'past-tech',
  },
  {
    id: 'black-powder-bomb',
    name: 'Black Powder Bomb',
    damage: 'D6',
    modifier: 'agility',
    specialRules: ['Explode', 'Thrown'],
    cost: 3,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'past-tech',
  },
];

// ============================================================================
// FUTURE TECH WEAPONS
// ============================================================================

export const futureTechWeapons28Psalms: Weapon[] = [
  // One-handed Melee Weapons
  {
    id: 'space-sword',
    name: 'Space Sword',
    damage: 'D8',
    modifier: 'strength',
    specialRules: ['AP'],
    cost: 10,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'future-tech',
  },
  {
    id: 'space-axe',
    name: 'Space Axe',
    damage: 'D6',
    modifier: 'strength',
    specialRules: ['Thrown'],
    cost: 3,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'future-tech',
  },
  {
    id: 'space-flail',
    name: 'Space Flail',
    damage: 'D8',
    modifier: 'strength',
    specialRules: ['Critical causes Bleeding'],
    cost: 5,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'future-tech',
  },
  {
    id: 'baton',
    name: 'Baton',
    damage: 'D6',
    modifier: 'strength',
    specialRules: ['Critical causes Dazed'],
    cost: 5,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'future-tech',
  },

  // Two-handed Melee Weapons
  {
    id: 'power-tool',
    name: 'Power Tool',
    damage: 'D6',
    modifier: 'strength',
    specialRules: [],
    cost: 5,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: false,
    techLevel: 'future-tech',
  },
  {
    id: 'katana',
    name: 'Katana',
    damage: 'D10',
    modifier: 'agility',
    specialRules: ['Criticals break enemy weapons'],
    cost: 20,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: false,
    techLevel: 'future-tech',
  },

  // One-handed Ranged Weapons (includes free ammo)
  {
    id: 'revolver',
    name: 'Revolver',
    damage: 'D6',
    modifier: 'presence',
    specialRules: ['Reload5', 'Ranged'],
    cost: 10,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: true,
    ammoTypeId: 'revolver-ammo',
    includesAmmoId: 'revolver-ammo',
    techLevel: 'future-tech',
  },
  {
    id: 'pistol',
    name: 'Pistol',
    damage: 'D6',
    modifier: 'presence',
    specialRules: ['Reload6', 'Ranged'],
    cost: 11,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: true,
    ammoTypeId: 'pistol-ammo',
    includesAmmoId: 'pistol-ammo',
    techLevel: 'future-tech',
  },

  // Two-handed Ranged Weapons (includes free ammo)
  {
    id: 'rifle',
    name: 'Rifle',
    damage: 'D8',
    modifier: 'presence',
    specialRules: ['AF2', 'Ranged 15', 'Cyber', 'Reload 4'],
    cost: 25,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: true,
    ammoTypeId: 'space-rifle-ammo',
    includesAmmoId: 'space-rifle-ammo',
    techLevel: 'future-tech',
  },
  {
    id: 'plas-mar',
    name: 'Plas-mar',
    damage: 'D10',
    modifier: 'presence',
    specialRules: ['Reload2', 'Explode', 'Ranged', 'AP'],
    cost: 35,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: true,
    ammoTypeId: 'plasma-cell-ammo',
    includesAmmoId: 'plasma-cell-ammo',
    techLevel: 'future-tech',
  },
  {
    id: 'pulse-rifle',
    name: 'Pulse Rifle',
    damage: 'D10',
    modifier: 'presence',
    specialRules: ['AF3', 'Ranged 15', 'Cyber', 'Reload 5'],
    cost: 30,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: true,
    ammoTypeId: 'pulse-rifle-ammo',
    includesAmmoId: 'pulse-rifle-ammo',
    techLevel: 'future-tech',
  },
  {
    id: 'shotgun',
    name: 'Shotgun',
    damage: 'D8',
    modifier: 'strength',
    specialRules: ['Explode', 'Ranged 6', 'Reload 2'],
    cost: 15,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: true,
    ammoTypeId: 'shotgun-ammo',
    includesAmmoId: 'shotgun-ammo',
    techLevel: 'future-tech',
  },
  {
    id: 'molten-slug-gun',
    name: 'Molten Slug Gun',
    damage: 'D12',
    modifier: 'strength',
    specialRules: ['AF2', 'Ranged 15', 'Cyber', 'Reload 5'],
    cost: 50,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: true,
    ammoTypeId: 'revolver-ammo',
    includesAmmoId: 'revolver-ammo',
    techLevel: 'future-tech',
  },
  {
    id: 'flamethrower',
    name: 'Flamethrower',
    damage: 'D6',
    modifier: 'strength',
    specialRules: ['Reload', 'Burn', 'Ranged6'],
    cost: 35,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: true,
    ammoTypeId: 'flame-ammo',
    includesAmmoId: 'flame-ammo',
    techLevel: 'future-tech',
  },
  {
    id: 'laser',
    name: 'Laser',
    damage: 'D6',
    modifier: 'presence',
    specialRules: ['Reload12', 'Cyber', 'Explode', 'Ranged'],
    cost: 20,
    slots: 2,
    category: 'weapon',
    isTwoHanded: true,
    isRanged: true,
    ammoTypeId: 'laser-ammo',
    includesAmmoId: 'laser-ammo',
    techLevel: 'future-tech',
  },

  // Consumables (treated as weapons in squad builder)
  {
    id: 'future-molotov',
    name: 'Molotov',
    damage: 'D6',
    modifier: 'agility',
    specialRules: ['Burn', 'Explode', 'Thrown'],
    cost: 3,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'future-tech',
  },
  {
    id: 'grenade',
    name: 'Grenade',
    damage: 'D6',
    modifier: 'agility',
    specialRules: ['Explode', 'Thrown', 'Template'],
    cost: 3,
    slots: 1,
    category: 'weapon',
    isTwoHanded: false,
    isRanged: false,
    techLevel: 'future-tech',
  },
];
